# Generated by Django 3.2.7 on 2021-09-24 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
